name: Docker build workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "The full name of the image (including user)"
      push:
        required: true
        type: boolean
        description: "Whether to push the image to Docker Hub or not"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: ${{ inputs.push }}
          tags: ${{ inputs.image-name }}
