name: Test

# This is only testing the Action
# DO NOT COPY THIS FILE

on:
  push:
    branches: [main]

jobs:
  build-only:
    uses: steeven9/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: some-org/some-image
      push: false
      dockerfile: Dockerfile-python
    secrets:
      DOCKERHUB_USERNAME: "none"
      DOCKERHUB_TOKEN: "none"
  build-and-push:
    uses: steeven9/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: steeven9/test
      push: true
      dockerfile: Dockerfile-python
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
